name: "Unit tests"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  xcode-tests:
    name: Xcode 26.0 (${{ matrix.name }})
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: iOS
          destination: platform=iOS Simulator,arch=arm64,OS=18.5,name=iPhone 16
        - name: macOS
          destination: platform=macOS,arch=arm64
        - name: visionOS
          destination: platform=visionOS Simulator,arch=arm64,OS=2.5,name=Apple Vision Pro
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install xcresultparser
      run: brew install xcresultparser
    - name: Create secrets file
      env:
        TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
      run: ./Scripts/CreateSecretsFile.sh
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    - if: ${{ matrix.name != 'macOS' }}
      name: Install platform runtime
      run: xcrun xcodebuild -downloadPlatform ${{ matrix.name }}
    - name: List destinations
      run: xcrun simctl list
    - name: Build and run tests
      run: |
        xcrun xcodebuild clean test \
          -project Kinova.xcodeproj \
          -scheme Kinova \
          -destination "${{ matrix.destination }}" \
          -resultBundlePath "Artifacts/Kinova.xcresult" \
    - if: always()
      name: Convert xcresult to JUnit
      run: xcresultparser -o junit Artifacts/Kinova.xcresult > Artifacts/Kinova.xml
    - if: always()
      name: Convert xcresult to HTML
      run: xcresultparser -o html Artifacts/Kinova.xcresult > Artifacts/Kinova.html
    - if: always()
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - if: always()
      name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - if: always()
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts (${{ matrix.name }})
        path: Artifacts
